name: AutoGluon Triton 'Bug'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      time:
        default: 120
      task:
        default: 363580


jobs:

  autogluon:
    name: run autogluon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Create venv
        run: python -m venv venv
      - name: Installation
        run: |
          source venv/bin/activate
          python -m pip install uv
          uv pip install autogluon openml
          uv pip install "autogluon.tabular[all,skex]" 
          uv pip list
      - name: Run
        run: |
          source venv/bin/activate
          python run_autogluon.py ${{ inputs.time }} ${{ inputs.task }}
